# PyTorch Basics

In [9]:
## Import Statements
import torch
import torch.nn as nn
import matplotlib.pyplot as plt

In [2]:
# Tensor - a matrix or an array, and their derivatives can be computed using autograd
a = torch.ones(3, 5)
print(a)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [3]:
sum = torch.sum(a, axis=1)
print(sum)

tensor([5., 5., 5.])


In [4]:
a = torch.ones(5,1)
print(a)
print(a.shape)

squeezed = torch.squeeze(a)
print(squeezed)
print(squeezed.shape)

unsqueezed = torch.unsqueeze(squeezed, dim=1)
print(unsqueezed)
print(unsqueezed.shape)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.]])
torch.Size([5, 1])
tensor([1., 1., 1., 1., 1.])
torch.Size([5])
tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.]])
torch.Size([5, 1])


In [5]:
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.first_layer = nn.Linear(4, 6)
        self.second_layer = nn.Linear(6, 6)
        self.final_layer = nn.Linear(6, 2)
    
    def forward(self, x):
        x = self.first_layer(x)
        x = self.second_layer(x)
        x = self.final_layer(x)
        return x

In [6]:
model = MyModel()
## Training Code

# Inference
example_datapoint = torch.randn(1, 4)
model(example_datapoint)

tensor([[-0.0592, -0.6339]], grad_fn=<AddmmBackward0>)

In [7]:
from jaxtyping import Float

torch.manual_seed(0)

class DigitRecognition(nn.Module):
    def __init__(self):
        super().__init__()
        # Define the architecture here
        self.layer1 = nn.Linear(784, 512)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(p=0.2)
        self.layer2 = nn.Linear(512, 10)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, images: Float[torch.Tensor, "..."]) -> Float[torch.Tensor, "..."]:
        # Return the model's prediction to 4 decimal places
        first_layer = self.dropout(self.relu(self.layer1(images)))
        return self.sigmoid(self.layer2(first_layer))

In [ ]:
model = DigitRecognition()

loss_function = nn.CrossEntropyLoss
optimizer = torch.optim.Adam(model.parameters())

epochs = 5
for epoch in range(epochs):
    for images, labels in train_dataloader:
        images = labels.view(images.shape[0], -784)
        
        # TRAINING BODY 
        model_prediction = model(images)
        optimizer.zero_grad()
        loss = loss_function(model_prediction, labels)
        loss
        optimizer.step()

In [8]:
model.eval()
for images, labels in test_dataloader:
    images = images.view(images.shape[0], 784)
    model_prediction = model(images)
    max, idx = torch.max(model_prediction, dim = 1)
    for i in range(len(images)):
        plt.imshow(images[i].view(28, 28))
        plt.show()
        print(idx[i].item())
    break

SyntaxError: invalid syntax (242891659.py, line 6)