# Singular Value Decomposition

SVD factorizes of a real or complex matrix into a rotation, followed by a rescaling followed by another rotation. It is colloquially known as the swiss-army knife of linear algebra due to its versatility and many places in application.


## Prereqs
### Eigenvector
An eigenvector of a square matrix $A$ is defined as a vector satisfying the equation
$$A\vec{x}=\lambda\vec{x}$$
and $\lambda$ is the corresponding eigenvalue. In other words, an eigenvector of A$$ is any vector that, when
multiplied by $A$, comes back as itself scaled by $\lambda$.

### Symmetric Positive Definite
A matrix is PSD if all of its eigenvalues $\geq$ 0, or equivalently a matrix $A$ for which $\vec{x}^TA\vec{x} \geq 0$ for any vector \$vec{x}$. To generate a $n \times n$ positive semi-definite matrix, we can take any matrix $X$ that has n columns and let $A = X^TX$


### Spectral Theorem
If $A$ is symmetric positive definite matrix, A can be decomposed into $A = S\lambda S^T$, where is S is a orthogonal matrix that contains the eigenvectors, $\lambda$ is a diagonal matrix filled with positive eigenvalues.


### Orthogonal Matrix 
An orthogonal matrix is a real square matrix whose columns and rows are orthonormal vectors, which means that the vectors are unit vectors and are orthogonal to each other. In other words, if $A$ is  orthogonal matrix, $A^TA = AA^T = I$. For example, consider 
$A = 
\begin{bmatrix}
\cos(x) & \sin(x)\\
-\sin(x) & \cos(x)
\end{bmatrix}
$, 
$$
AA^T = 
\begin{bmatrix}
\cos(x) & \sin(x)\\
-\sin(x) & \cos(x)
\end{bmatrix}
\begin{bmatrix}
\cos(x) & -\sin(x)\\
\sin(x) & \cos(x)
\end{bmatrix} =
\begin{bmatrix}
\cos^2(x) + \sin^2(x) & -\cos(x)\sin(x)+\sin(x)\cos(x)\\
-\sin(x)\cos(x)+\cos(x)\sin(x) & \sin^2(x)+\cos^2(x)
\end{bmatrix}=
\begin{bmatrix}
1 & 0\\
0 & 1
\end{bmatrix}
$$
Some properties of orthogonal matrix A include:
-  Transpose and Inverse are equal. i.e. $A^{-1}=A^T$
-  The product of A and its transpose is an identity matrix. i.e $A^TA = AA^T = I$
-  Determinant is $det(A) = \pm 1$ Thus, an orthogonal matrix is always non-singular as its determinant is not 0.
-  A diagonal matrix with elements to be 1 or -1 is always orthogonal
-  $A^T$ is also orthogonal. Since $A^-1=A^T$, $A^{-1}$ is also orthogonal
-  The eigenvalues of $A$ are $\pm 1$ and the eigenvectors are orthogonal
-  An identity matrix (I) is orthogonal.
-  Orthogonal matrices applied as a transformation preserves the length of vectors, and the angles between vectors. In other words, $||Av|| = ||v||$, and $(Au)\cdot(Av) = u \cdot v$
-  In two dimensions, a rotation matrix $R(\theta)$ that rotates vectors counter clockwise by an angle $\theta$ is given by 
$
\begin{bmatrix}
\cos(\theta) & -\sin(\theta)\\
\sin(\theta) & \cos(\theta)
\end{bmatrix}
$
- In 3D, orthogonal matrices (with determinant 1) represent rotations around an axis. For example, the rotation matrix around the $z$-axis by an angle $\theta$ is given by 
$
\begin{bmatrix}
\cos(\theta) & -\sin(\theta) & 0\\
\sin(\theta) & \cos(\theta) & 0 \\
0 & 0 & 1
\end{bmatrix}
$
- They can represent pure rotations (when the determinant is 1) or reflections combined with rotations (when the determinant is -1)
- Orthogonal matrices preserve orthonormality: If the original vectors are orthonormal, their images under an orthogonal transformation remain orthonormal
- Because orthogonal matrices preserve lengths and angles, they perform transformations that resemble rotating vectors around the origin without changing their shape or size


### Diagonal Matrix
A diagonal matrix is a matrix in which the entries outside the main diagonal are all zero. Diagonal matrices can be thought of as stretches because they scale each component of a vector independently along the corresponding coordinate axis.


Some properties of diagonal matrix include:
- Diagonal matrices are typically square matrices, but not always. So long as all the non-zero elements have the same row & column index, the matrix is diagonal. A square diagonal matrix can have extra zero rows and/or columns added and still stay diagonal.
- The sum of two diagonal matrices is a diagonal matrix
- The product of two diagonal matrices is a diagonal matrix where the elements of its principal diagonal are the products of corresponding elements
- Diagonal matrices are commutative under both addition and multiplication.
- The rank is the number of non-zeroes on the diagonal.
- The eigenvalues are just the diagonal numbers

### Eigendecomposition
Eigendecomposition is the factorization of a matrix into a canonical form, whereby the matrix is represented in terms of its eigenvalues and eigenvectors. It can only be done of a square diagonalizable matrix. 
This can be determined in a few ways after computing the eigenvalues and eigenvectors
 - Check that for each eigenvalue, its number of times it appears as a root of the characteristic polynomial is the same as the number of linearly independent eigenvectors associated with that eigenvalue A.
 - Check if you have $n$ linearly independent eigenvectors 
   - If you have n-distinct eigenvalues, this holds true
- Check if the Jordan of the matrix is diagonal
- Check if the matrix is symmetric

If A is symmetric, then there exists $S$ and $\Lambda$ such that $A=S\Lambda S^T$ because for symmetric A the eigenvectors in S are orthonormal, so S is Orthogonal.

The intuition is as follows. Supposed we have a $n$ linearly independent eigenvectors $x_i$ of A
Let's put them in columns of a matrix S - eigenvectors
$$S = 
\begin{bmatrix}
| & & |\\
x_1 & \cdots & x_n\\
| & & |\\
\end{bmatrix}
$$ 
Now what if we multiply $AS$?
Since all these $x_i$ are eigenvectors, $Ax_i=\lambda_ix_i$
Thus $AS = A
\begin{bmatrix}
| & | & & |\\
x_1 & x_2 & & \cdots & x_n\\
| & | & & |\\
\end{bmatrix} = 
\begin{bmatrix}
| & | & & |\\
\lambda_1 x_1 & \lambda_2 x_2 & & \cdots & \lambda_m x_n\\
| & | & & |\\
\end{bmatrix} =
\begin{bmatrix}
| & | & & |\\
x_1 & x_2 & & \cdots & x_n\\
| & | & & |\\
\end{bmatrix}
\begin{bmatrix}
\lambda_1 & 0 & \cdots & 0 \\
0 & \lambda_2 & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & \lambda_n
\end{bmatrix}
$

Let's call the diagonal matrix $\Lambda = 
\begin{bmatrix}
\lambda_1 & 0 & \cdots & 0 \\
0 & \lambda_2 & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & \lambda_n
\end{bmatrix}
$

so $AS = S\Lambda \Rightarrow A = S\Lambda A^{-1}$


## Interpretations of SVD
Every $m \times n$ matrix can be factored into $A_{m \times n}=U_{m \times m}\Sigma_{m \times n} V^T_{n \times n}$. The values in $\Sigma$ are called the singular values. The columns in $U$ are known as left singular vectors, and the rows in $V^T$ are known as the left singular vectors. 

SVD just states that all matrices are a sequential application of a three linear transformations. $V^T$ is a orthonormal matrix that applies a rotation such that the right singular vectors return to the standard basis.  $\Sigma$ is a rectangularly diagonal matrix composed of a dimension eraser that reduces the dimensionality from $R^n$ to $R^m$. It also performs a stretch on each axis by the corresponding singular values, and the final step, orthogonal matrix $U$ rotates the standard basis to the left singular vectors.

Another interpretation of SVD is that a high rank matrix $A$ is a summation of k rank-1 matrices, where $A = \sum_{i=1}^{k}\sigma_{i}u_iv_i^T$ 

## What the SVD tries to solve

Problem: Given matrix $A$, we want to find a set of orthogonal set of a vectors that when transformed by our matrix will remain orthogonal. We can write down the problem in 2-d space with the equations below:
$$Av_1=y_1$$
$$Av_2=y_2$$
We can split up the y values into a direction and magnitude so that $u_1$ and $u_2$ are unit vectors.
$$Av_1=\sigma_1u_1$$
$$Av_2=\sigma_2u_2$$
We can rewrite this equation in matrix form to make it more general.
$$A 
\begin{bmatrix}
v_1 & v_2
\end{bmatrix} =
\begin{bmatrix}
\sigma_1u_1 & \sigma_2u_2
\end{bmatrix}
=
\begin{bmatrix}
u_1 & u_2
\end{bmatrix}
\begin{bmatrix}
\sigma_1 & 0\\
0 & \sigma_2
\end{bmatrix} = U\Sigma \Rightarrow A = U\Sigma V^{-1} = U\Sigma V^T
$$

## How to compute the SVD
To find U, we will multiply both sides by $A^T$. Since U is a orthogonal matrix, $U^T = U^{-1}$ 
$$A^TA=(U\Sigma V^T)^T(U\Sigma V^T)=V\Sigma U^TU\Sigma V^T=V\Sigma^2V^T$$
So know we know V is given by the eigendecomposition of $A^TA$, and out condition that V be orthogonal is satisfied because $A^TA$ is symmetric, and the eigenvectors of a symmetric matrix are orthogonal

Similarly,
$$AA^T=(U\Sigma V^T)(U\Sigma V^T)^T=U\Sigma V^TV\Sigma U^T=U\Sigma^2U^T$$
So know we know U is given by the eigendecomposition of $AA^T$, and out condition that U be orthogonal is satisfied because $AA^T$ is symmetric, and the eigenvectors of a symmetric matrix are orthogonal

### Example
Find the singular value decomposition of the matrix $C = \begin{bmatrix} 5 & 5 \\ -1 & 7\end{bmatrix}$
We want $C=U\Sigma V^T$, and $CV=U\Sigma$

**Finding V**
$$C^TC=V\Sigma^T \Sigma V^T = \begin{bmatrix} 5 & -1 \\ 5 & 7\end{bmatrix} \begin{bmatrix} 5 & 5 \\ -1 & 7\end{bmatrix} = \begin{bmatrix} 26 & 18 \\ 18 & 74\end{bmatrix}$$

To find the eigenvectors and eigenvalues of $A^TA$, we do the following
$$
\text{det}(C^TC-\lambda I) = \text{det}\left(\begin{bmatrix} 26-\lambda & 18 \\ 18 & 74-\lambda\end{bmatrix}\right) = \lambda^2-100\lambda+1600 = (\lambda-20)(\lambda-80)
$$ 
So we know the eigenvalues are 20 and 80.
To find the eigenvector for $\lambda = 20$
$$C^TC-20I= \begin{bmatrix} 6 & 18 \\ 18 & 54\end{bmatrix}$$
Since the second column is three times the first column, We can see that the null space can be $\begin{bmatrix} -3 & 1\end{bmatrix}$, but we want a unit vector so find the null space to be $\begin{bmatrix} \frac{-3}{\sqrt{10}} & \frac{1}{\sqrt{10}}\end{bmatrix}$

To find the eigenvector for $\lambda = 80$
$$C^TC-80I= \begin{bmatrix} -54 & 18 \\ 18 & -6\end{bmatrix}$$
The null space is then  $\begin{bmatrix} \frac{1}{\sqrt{10}} & \frac{3}{\sqrt{10}}\end{bmatrix}$.

Thus, $V^T = \begin{bmatrix} \frac{1}{\sqrt{10}} & \frac{3}{\sqrt{10}}\\ \frac{-3}{\sqrt{10}} & \frac{1}{\sqrt{10}}\end{bmatrix}$ and $\Sigma = \begin{bmatrix} 4\sqrt{5} & 0 \\ 0 & 2\sqrt{5}\end{bmatrix}$

**Finding U**
$$CV=U\Sigma= \begin{bmatrix} 5 & 5 \\ -1 & 7\end{bmatrix} \begin{bmatrix} \frac{1}{\sqrt{10}} & \frac{-3}{\sqrt{10}}\\ \frac{3}{\sqrt{10}} & \frac{1}{\sqrt{10}}\end{bmatrix} = \begin{bmatrix} 2\sqrt{10} & -\sqrt{10}\\ 2\sqrt{10} & \sqrt{10}\end{bmatrix} = \begin{bmatrix} \frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}}\\\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}}\end{bmatrix} \begin{bmatrix} 4\sqrt{5} & 0 \\ 0 & 2\sqrt{5}\end{bmatrix}$$

Thus, 
$
U = \begin{bmatrix} \frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}}\\\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}}\end{bmatrix}
$

$$
C = 
\begin{bmatrix} \frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}}\\\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}}\end{bmatrix}
\begin{bmatrix} 4\sqrt{5} & 0 \\ 0 & 2\sqrt{5}\end{bmatrix}
 \begin{bmatrix} \frac{1}{\sqrt{10}} & \frac{3}{\sqrt{10}}\\ \frac{-3}{\sqrt{10}} & \frac{1}{\sqrt{10}}\end{bmatrix} = U\Sigma V^T
$$


In [1]:
import numpy as np

# Define the matrix C
C = np.array([[5, 5],
              [-1, 7]])

# Step 1: Compute C^T C
CTC = C.T @ C

# Step 2: Compute eigenvalues and eigenvectors for V and Sigma
eigenvalues, eigenvectors = np.linalg.eigh(CTC)
# Sorting eigenvalues and corresponding eigenvectors in descending order
sorted_indices = np.argsort(eigenvalues)[::-1]
V = eigenvectors[:, sorted_indices]
Sigma = np.sqrt(np.diag(eigenvalues[sorted_indices]))

# Step 3: Compute U
U = C @ V @ np.linalg.inv(Sigma)

# Normalizing U's columns to ensure they are unit vectors
U = U / np.linalg.norm(U, axis=0)

# Verify the decomposition C = U Sigma V^T
C_reconstructed = U @ Sigma @ V.T

print("Matrix C:\n", C)
print("Reconstructed C:\n", C_reconstructed)
print("U:\n", U)
print("Sigma:\n", Sigma)
print("VT:\n", V.T)

Matrix C:
 [[ 5  5]
 [-1  7]]
Reconstructed C:
 [[ 5.  5.]
 [-1.  7.]]
U:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
Sigma:
 [[8.94427191 0.        ]
 [0.         4.47213595]]
VT:
 [[ 0.31622777  0.9486833 ]
 [-0.9486833   0.31622777]]


In [2]:
import torch

# Step 1: Define the matrix C
C = torch.tensor([[5.0, 5.0], [-1.0, 7.0]])

# Step 2: Compute the SVD using PyTorch's built-in function
U, S, V = torch.svd(C)

# Display the results
print("Matrix C:")
print(C)
print("\nMatrix U:")
print(U)
print("\nSingular Values (S):")
print(S)
print("\nMatrix VT:")
print(V.T)

# Reconstruct C using U, S, V^T
S_matrix = torch.diag(S)
C_reconstructed = torch.mm(U, torch.mm(S_matrix, V.t()))
print("\nReconstructed C (UΣV^T):")
print(C_reconstructed)

Matrix C:
tensor([[ 5.,  5.],
        [-1.,  7.]])

Matrix U:
tensor([[ 0.7071,  0.7071],
        [ 0.7071, -0.7071]])

Singular Values (S):
tensor([8.9443, 4.4721])

Matrix VT:
tensor([[ 0.3162,  0.9487],
        [ 0.9487, -0.3162]])

Reconstructed C (UΣV^T):
tensor([[ 5.0000,  5.0000],
        [-1.0000,  7.0000]])


### Application: Find the direction of maximum stretching
Problem: In what direction does matrix $A$ stretch a unit vector the most? or $$\underset{x:||x||=1}{\arg\max} ||Ax|| \equiv \underset{x:||x||=1}{\arg\max} ||Ax||^2 = \underset{x:||x||=1}{\arg\max} (Ax)^T(Ax) = \underset{x:||x||=1}{\arg\max}  x^TA^TAx$$

Now lets write out the eigenvalue expression of A^TA
$$
(A^TA)x=\lambda x\\
x^T(A^TA)x=\lambda x^Tx=\lambda\\
$$
This shows that to maximize this quantity, choose x to be the eigenvector with the maximum eigenvalue. The eigenvector of $A^TA$ with the largest eigenvalue is the first column of U, thus
$$\underset{x:||x||=1}{\arg\max}  x^TA^TAx = u_1$$

#### Application from Strang's Book
- If we had a spreadsheet that contains the grades for all courses, there would be a column for each student and a row for each course: The entry $a_{ij}$ would be the grade.Then $\sigma_1u_1v_1^T$ could have $u_1 = \text{combination course}$ and $v_1 = \text{combination student}$. And $\sigma_1$ would be the grade for those combinations: the highest grade.
- The matrix $A$ could count the frequency of key words in a journal : A different article for each column of $A$ and a different word for each row. The whole journal is indexed by the matrix A and the most important information is in $\sigma_1u_1v_1^T$  Then $\sigma_1$ is the largest frequency for a hyperword (the word combination $u_1$ )in the hyperarticle $v_1$.

### Final notes
Given rank $r$ of matrix $A$
- the vectors $v_1, ..., v_r$ is the orthonormal basis for the row space.
- the vectors $u_1, ..., u_r$ is the orthonormal basis for the column space.
- the vectors $v_{r+1}, ..., v_n$ is the orthonormal basis for the null space.
- the vectors $u_{r+1}, ..., v_m$ is the orthonormal basis for the null space of $A^T$ (left nullspace).
- $Av_i=\sigma _iu_i$
- The singular values in $\Sigma$ are ordered in descending order in magnitude ($\sigma_1 \geq \sigma_2 \geq ... \geq \sigma_r > 0$)
- The number of nonzero $\sigma$ values in $\Sigma$ give us the rank
- The numbers $\sigma_1^2$, $\sigma_2^2$, ..., $\sigma_r^2$ are the nonzero eigenvalues of $AA^T$ and $A^TA$
- $A = \sigma_1u_1v_1^T + \sigma_2u_2v_2^T + ... +\sigma_ru_rv_r^T$ and $\sigma_1$ is the maximum of the ratio $\frac{||Ax||}{||x||}$

References:
- https://www.youtube.com/watch?v=mBcLRGuAFUk&t=44s
- https://www.cuemath.com/algebra/orthogonal-matrix/
- https://www.youtube.com/watch?v=vSczTbgc8Rc&t=400s
- https://www.youtube.com/watch?v=CpD9XlTu3ys
- https://www.youtube.com/watch?v=cOUTpqlX-Xs
- https://pillowlab.princeton.edu/teaching/statneuro2018/slides/notes03a_SVDandLinSys.pdf
- https://math.mit.edu/classes/18.095/2016IAP/lec2/SVD_Notes.pdf#page=1.49